account/urls.py
from django.urls import path
from . import views

app_name = 'account'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('memberinfo/<int:pk>/', views.MemberinfoView.as_view(), name='memberinfo'),
    path('changeinfo/<int:pk>/', views.ChangeinfoView.as_view(), name='changeinfo'),
    path('confirminfo/<int:pk>/',
         views.ConfirminfoView.as_view(), name='confirminfo'),
    path('succeed/', views.SucceedinfoView, name='succeed'),
]

blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.post_list, name='post_list'),
    # http:127.0.0.1:8000/post/<pkの値>/で表示
    path('post/<int:pk>/', views.post_detail, name='post_detail'),
    path('post/new', views.post_new, name='post_new'),
    path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('drafts/', views.post_draft_list, name='post_draft_list'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView, name='home'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('account/', include('account.urls', namespace='account')),
    path('account/', include('django.contrib.auth.urls')),
    path('', include('home.urls', namespace='home')),
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


def HomeView(request):
    return render(request, "home/index.html")

home/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf8">
    <title>{% block title %}会員サイト{% endblock%}</title>
</head>

<body>
    <div class="container">
        <header>
            <nav>
                <ul>
                    {% if user.id  %}
                    <!-- ログイン時 -->
                    {{ user.username }}様
                    <a href="{% url 'account:memberinfo'  pk=user.pk %}">会員情報の確認</a>
                    <a href="{% url 'logout' %}">ログアウト</a>
                    {% else %}
                    <!-- ログインしていない時 -->
                    <a href="{% url 'login' %}">ログイン</a>
                    <a href="{% url 'account:signup'%}">会員登録</a>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="content">
            {% block content %}{% endblock%}
        </div>
    </div>
</body>

</html>